# Generated by Django 3.2 on 2021-04-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporation', '0008_delete_stockprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volume', models.IntegerField()),
                ('bprc_adj', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hi_adj', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lo_adj', models.DecimalField(decimal_places=2, max_digits=20)),
                ('prc_adj', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporation.ticker')),
            ],
            options={
                'db_table': 'stock_prices',
            },
        ),
    ]
