# Generated by Django 3.2 on 2021-04-28 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporation', '0008_auto_20210428_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('stock_name', models.CharField(max_length=50)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporation.corporation')),
            ],
            options={
                'db_table': 'tickers',
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volume', models.IntegerField()),
                ('bprc_adj', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hi_adj', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lo_adj', models.DecimalField(decimal_places=2, max_digits=20)),
                ('prc_adj', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ticker')),
            ],
            options={
                'db_table': 'stock_prices',
            },
        ),
    ]
