# Generated by Django 3.2 on 2021-04-19 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocode', models.CharField(max_length=8)),
                ('coname', models.CharField(max_length=200)),
                ('coname_eng', models.CharField(max_length=200, null=True)),
                ('stock_name', models.CharField(max_length=200, null=True)),
                ('ticker', models.CharField(max_length=20, null=True, unique=True)),
                ('jurir_no', models.CharField(max_length=50, null=True, unique=True)),
                ('bizr_no', models.CharField(max_length=50, null=True, unique=True)),
                ('adres', models.CharField(max_length=200, null=True)),
                ('hm_url', models.CharField(max_length=500, null=True)),
                ('ir_url', models.CharField(max_length=500, null=True)),
                ('phn_no', models.CharField(max_length=50, null=True)),
                ('fax_no', models.CharField(max_length=50, null=True)),
                ('est_dt', models.DateField(null=True)),
            ],
            options={
                'db_table': 'corporations',
            },
        ),
        migrations.CreateModel(
            name='MainShareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcept_no', models.CharField(max_length=20)),
                ('nm', models.CharField(max_length=50)),
                ('bsis_posesn_stock_co', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bsis_posesn_stock_qota_rt', models.DecimalField(decimal_places=2, max_digits=20)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporation.corporation')),
            ],
            options={
                'db_table': 'main_shareholders',
            },
        ),
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('main_shareholder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corporation.mainshareholder')),
            ],
            options={
                'db_table': 'stock_types',
            },
        ),
        migrations.CreateModel(
            name='IndustryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('corporation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corporation.corporation')),
            ],
            options={
                'db_table': 'industry_codes',
            },
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(null=True)),
                ('sales_ind', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('ebit_ind', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('ni_ind', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('sales_con', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('ebit_con', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('ni_con', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('ni_control_con', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporation.corporation')),
            ],
            options={
                'db_table': 'income_statements',
            },
        ),
        migrations.CreateModel(
            name='CurrencyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('income_statement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corporation.incomestatement')),
            ],
            options={
                'db_table': 'currency_units',
            },
        ),
        migrations.CreateModel(
            name='CorporationClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1)),
                ('symbol_description', models.CharField(max_length=20)),
                ('corporation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corporation.corporation')),
            ],
            options={
                'db_table': 'corporation_classifications',
            },
        ),
        migrations.CreateModel(
            name='CeoName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporation.corporation')),
            ],
            options={
                'db_table': 'ceo_names',
            },
        ),
        migrations.CreateModel(
            name='AccountingMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('corporation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corporation.corporation')),
            ],
            options={
                'db_table': 'accounting_months',
            },
        ),
    ]
