# Generated by Django 3.2 on 2021-04-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='is_financial_corporation',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
