# Generated by Django 3.2 on 2021-04-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingmonth',
            name='corporation',
        ),
        migrations.RemoveField(
            model_name='corporationclassification',
            name='corporation',
        ),
        migrations.RemoveField(
            model_name='currencyunit',
            name='income_statement',
        ),
        migrations.RemoveField(
            model_name='industrycode',
            name='corporation',
        ),
        migrations.RemoveField(
            model_name='stocktype',
            name='main_shareholder',
        ),
        migrations.AddField(
            model_name='corporation',
            name='accounting_month',
            field=models.ForeignKey(default=1000000, on_delete=django.db.models.deletion.RESTRICT, to='corporation.accountingmonth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corporation',
            name='corporation_classification',
            field=models.ForeignKey(default=100000, on_delete=django.db.models.deletion.RESTRICT, to='corporation.corporationclassification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corporation',
            name='industry_code',
            field=models.ForeignKey(default=100000, on_delete=django.db.models.deletion.RESTRICT, to='corporation.industrycode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='currency_unit',
            field=models.ForeignKey(default=100000, on_delete=django.db.models.deletion.RESTRICT, to='corporation.currencyunit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainshareholder',
            name='stock_type',
            field=models.ForeignKey(default=100000, on_delete=django.db.models.deletion.RESTRICT, to='corporation.stocktype'),
            preserve_default=False,
        ),
    ]
