# Generated by Django 3.2 on 2021-04-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0002_corporation_is_financial_corporation'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestatement',
            name='asset_con',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='asset_ind',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
