# Generated by Django 3.2 on 2021-04-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0003_auto_20210420_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConglomerateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'conglomerate_types',
            },
        ),
        migrations.RemoveField(
            model_name='corporation',
            name='ticker',
        ),
        migrations.AlterField(
            model_name='corporation',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporation.corporation')),
            ],
            options={
                'db_table': 'tickers',
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volume', models.IntegerField()),
                ('bprc_adj', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hi_adj', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lo_adj', models.DecimalField(decimal_places=2, max_digits=20)),
                ('prc_adj', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporation.ticker')),
            ],
            options={
                'db_table': 'stock_prices',
            },
        ),
        migrations.CreateModel(
            name='Conglomerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designate', models.DateField(null=True)),
                ('conglomerate', models.CharField(max_length=50, null=True)),
                ('tycoon', models.CharField(max_length=50, null=True)),
                ('nfirms', models.IntegerField(null=True)),
                ('nfirms_public', models.IntegerField(null=True)),
                ('at_regular', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('teq', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('sale', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('ni', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('gcode', models.CharField(max_length=50, unique=True)),
                ('conglomerate_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='corporation.conglomeratetype')),
                ('currency_unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='corporation.currencyunit')),
            ],
            options={
                'db_table': 'conglomerates',
            },
        ),
        migrations.AddField(
            model_name='corporation',
            name='conglomerate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='corporation.conglomerate'),
        ),
    ]
