# Generated by Django 3.2 on 2021-04-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0004_auto_20210427_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporation',
            name='conglomerate',
        ),
        migrations.CreateModel(
            name='ConglomerateCorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conglomerate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporation.conglomerate')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporation.corporation')),
            ],
        ),
        migrations.AddField(
            model_name='corporation',
            name='conglomerate',
            field=models.ManyToManyField(through='corporation.ConglomerateCorporation', to='corporation.Conglomerate'),
        ),
    ]
