# Generated by Django 3.2 on 2021-04-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0005_auto_20210427_1715'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conglomeratecorporation',
            table='conglomerates_corporations',
        ),
    ]
