# Generated by Django 3.2 on 2021-04-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0006_alter_conglomeratecorporation_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='name',
            new_name='stock_name',
        ),
    ]
