# Generated by Django 3.2 on 2021-04-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0007_rename_name_ticker_stock_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockPrice',
        ),
    ]
