# Generated by Django 3.2 on 2021-04-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_accountingmonth_ceoname_corporation_corporationclassification_currencyunit_incomestatement_industryc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='jurir_no',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
