# Generated by Django 3.2 on 2021-05-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_gridlayout_is_displyed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='이름', max_length=100),
            preserve_default=False,
        ),
    ]
