# Generated by Django 3.2 on 2021-05-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='01012345678', max_length=30),
            preserve_default=False,
        ),
    ]
